apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: test
spec:
  # ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        env:
            - name: event
              valueFrom:
                configMapKeyRef:
                  name: event-config
                  key: event
      restartPolicy: Never
  backoffLimit: 4
